Cosmic-Overlord/TerraGov-Marine-Corps

code/modules/client/preferences_ui.dm
Кнопка Radial stacks wheel в настройках игры не отображалась зеленым цветом при включении опции.
Визуально понятно, что опция включена.
:cl:
code: Значение кнопки в интерфейсе теперь 0 или 1.
/:cl:
=> Фикс кнопки Radial stacks wheel

code/modules/client/client_procs.dm
Добавил проверку на нул.
Не будет ошибок.
:cl:
fix: Добавлена проверка на null в change_view(new_size).
/:cl:
=> Фикс нула в change_view

code/modules/mob/living/carbon/xenomorph/embryo.dm
Лявра теперь будет закапываться при бурсте из человека, если её никто не контролирует.
Блундир попросил - я сделяль
:cl:
balance: Лявра теперь будет закапываться при бурсте из человека, если её никто не контролирует.
/:cl:
=> Лявра закапывается при бурсте

code/__DEFINES/preferences.dm, code/controllers/configuration/entries/general.dm, code/datums/view.dm
Ничего заметного для игроков
Логичность и читаемость кода
:cl:
fix: переделал дейфайны вадйскрина, для лучшей читаемости
/:cl:
=> Переделал дефайны вайдскрина

code/game/objects/structures/droppod.dm, tgui/packages/tgui/interfaces/Droppod.tsx
Небольшое обновление дропподов.
Пролетая гостом над дропподом игра больше не будет подвисать. Появилась возможность запускать других игроков.
:cl:
add: Возможность в грабе положить человека в дроппод
add: Возможность переносом куклы положить человека в дроппод
add: Добавлен верб /obj/structure/droppod/verb/eject()
del: Убран верб /obj/structure/droppod/verb/openui()
code: Переименована кнопка Exit Drop pod - Exit Pod в Pod door - Eject occupant
code: Открытие меню при нажатии на дроппод
/:cl:
=> Улучшение дропподов

code/game/objects/machinery/vending/new_marine_vendors.dm
Фикс набора
Об маяк должен быть у фк
:cl:
add: Добавлен маяк об в набор фк с джагер армором
/:cl:
=> ob beacon for jaeger fc bundle

code/controllers/subsystem/explosions.dm, code/game/atoms_movable.dm
При броске предметов в большие объекты они не будут двигаться. При взрыве большие объекты тоже не будут двигаться.
Мех нельзя будет двигать, кидая в него мусор. Взрывы гранат не будут откидывать мех, квину и тд. в космос.
:cl:
code: В /atom/movable/proc/throw_impact(atom/hit_atom, speed, bounce) добавлена проверка на move_resist.
code: В /datum/controller/subsystem/explosions/fire(resumed) добавлена проверка на move_resist.
/:cl:
=> Фикс отбрасывания

code/game/objects/machinery/computer/camera_advanced.dm, code/game/objects/structures/droppod.dm, tgui/packages/tgui/interfaces/Droppod.tsx
Теперь место приземления дроппода можно выбрать при помощи камеры. Ручной ввод координат все еще остался.
Маринам удобно выбирать, где припарковать свой железный гроб.
:cl:
add: Возможность использовать камеру в дропподе.
add: Кнопка входа в режим камеры.
code: В /mob/camera/aiEye/remote поле origin содержит obj, а не obj/machinery
/:cl:
=> Добавление камеры дропподу

code/game/objects/machinery/computer/nuke_disk_generator.dm, tgui/packages/tgui/interfaces/NukeDiskGenerator.tsx
Теперь компьютер генерирующий диск для нюки имеет модный ТГУИ.
Красивый, не лаганный, не баганный интерфейс. Не надо нажимать на компьютер 500 раз чтобы видеть оставшееся время.
:cl:
add: TGUI для /obj/machinery/computer/nuke_disk_generator
del: Старый интерфейс /obj/machinery/computer/nuke_disk_generator
/:cl:
=> Обновление интерфейса компа нюки

code/game/objects/machinery/autodoc.dm, tgui/packages/tgui/interfaces/Autodoc.js
Автодок теперь использует TGUI
Чем меньше старого интерфейса, тем лучше.
:cl:
add: TGUI для /obj/machinery/autodoc_console
del: Старый интерфейс /obj/machinery/autodoc_console
/:cl:
=> Обновление интерфейса автодока

code/game/objects/machinery/sleeper.dm, tgui/packages/tgui/interfaces/Sleeper.js
Слипер теперь использует TGUI
Красиво, модно, молодежно
:cl:
add: TGUI для /obj/machinery/sleep_console
del: Старый интерфейс /obj/machinery/sleep_console
/:cl:
=> Обновление интерфейса слипера

code/modules/mob/living/living_defines.dm, code/modules/projectiles/gun_system.dm
Фикс Джаггла
Абузить плохо
:cl:
balance: Фикс джаггла
/:cl:
=> Фикс джаггла

code/__DEFINES/mode.dm, code/game/objects/structures/ladders.dm, code/modules/admin/panels/player_panel.dm, code/modules/admin/topic.dm, code/modules/mob/living/carbon/xenomorph/attack_alien.dm, code/modules/mob/living/carbon/xenomorph/hive_datum.dm, code/modules/xenomorph/xeno_structures.dm
Быстро фикс, Быстро баланс
:cl:
balance: Несколько балансных изменений
fix:  Хаггеры теперь могут использовать лестницы и туннели 
/:cl:
=> Facehuggers fix and balance change

code/modules/projectiles/guns/revolvers.dm, code/modules/projectiles/guns/shotguns.dm
Добавил значения задержек для револьверов и двустволок, которые забыл в изначальном ПРе
:cl:
fix: добавил значения задержек для револьверов и двустволок, которые забыл в изначальном ПРе
/:cl:
=> фикс джаггла для двустволок и ревиков

code/modules/mob/living/carbon/xenomorph/castes/facehugger/castedatum_facehugger.dm, code/modules/mob/living/carbon/xenomorph/embryo.dm, code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Из-за бага эмбрионы, полученный от разумных фейсхаггеров никогда не вырастают. Этот пр чинит данный баг.
Баг фикс гуд
:cl:
fix: Фикс бага фейсхаггеров
/:cl:
=> Fix embryo facehuggers

code/game/objects/machinery/adv_med.dm, tgui/packages/tgui/interfaces/BodyScanner.js
Бодисканер теперь использует TGUI
Билд становится технологичней.
:cl:
add: TGUI для /obj/machinery/body_scanconsole
del: Старый интерфейс /obj/machinery/body_scanconsole
/:cl:
=> Обновление интерфейса бодисканера

code/datums/loadout/loadout.dm, code/datums/loadout/loadout_manager.dm, code/modules/tgui_input/alert.dm, tgui/packages/tgui/interfaces/LoadoutViewer/index.tsx
Добавлена кнопка перезаписи лодаута. Добавлен запрос подтверждения удаления/перезаписи лодаута. Лодауты с одинаковыми именами в рамках одной профессии нельзя добавлять.
Удобней лодаут меню и теперь игроки случайно не будут удалять/перезаписывать свои лодауты.
:cl:
add: Кнопка "Rewrite loadout" в LoadoutNavigator
add: Окно подтверждения в /datum/loadout/ui_act(action, list/params, datum/tgui/ui, datum/ui_state/state)
add: Объект источник src_object в /datum/tgui_alert
code: В /datum/loadout_manager/ui_act(action, list/params, datum/tgui/ui, datum/ui_state/state) добавлена проверка имени лодаута при создании
/:cl:
=> Добавление кнопки в лодауте

code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
Если в руках у хантера есть хагер - он не невидим, а прозрачен.
Я не знаю, я не знаю..
:cl:
del: смешное захагирования маров, не дали даже просто значок сделать видимым, "слишком сложно успеть"
:cl:
=> Held facehuggers change alpha (hunter)

code/_onclick/xeno.dm, code/game/objects/machinery/doors/airlock.dm, code/game/objects/structures/ladders.dm, code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm, code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm, code/modules/mob/living/carbon/xenomorph/castes/facehugger/abilities_facehugger.dm, code/modules/mob/living/carbon/xenomorph/egg.dm, code/modules/xenomorph/xeno_structures.dm
Атаки хаггера теперь учитывают кд на атаку
Хаггер теперь может открывать вентиляцию!
ДВА ПО ЦЕНЕ ОДНОГО
<b>BIG SHOT
BIG SHOT</b>
BugFix
<b><del>[BIG SHOT]</del></b>
:cl:
fix: Attack delay for hugger attack
/:cl:
=> Attack delay for facehugger

tgui/packages/tgui/interfaces/HiveStatus.tsx
Окно хайва увеличено
Все видно и влазит
:cl:
code: width 700->900
/:cl:
=> Увеличение окна статуса хайва

code/modules/mob/living/carbon/xenomorph/castes/panther/castedatum_panther.dm
+40хп во всех возрастах, всё ещё меньше, чем у хантера 
На слабость пантеры всё ещё ноют, не понимал этого нытья ровно до того момента, как поймал всего одно ПБ дробовиком и улетел в госты(((( умирать обидно, вот вам ПРка
:cl:
balance: panther max_health += 40
/:cl:
=> panther lifetime buff

code/game/objects/machinery/nuclearbomb.dm, tgui/packages/tgui/interfaces/NuclearBomb.tsx
Нюка теперь использует TGUI
Можно смотреть как красиво уходит таймер на нюке
:cl:
add: TGUI для /obj/machinery/nuclearbomb
del: Старый интерфейс /obj/machinery/nuclearbomb
/:cl:
=> Обновление интерфейса нюки

code/game/turfs/space.dm
Космос теперь наносит урон
Космические путешественники исчезнут
:cl:
fix: Постоянное удаление/добавление дебафа каждый пройдённый тайл космоса
/:cl:
=> Фикс космоса

code/modules/mob/say.dm, tgui/packages/tgui-say/constants/index.tsx
Теперь для доступа в канал можно ввести русский символ. Например: :m :ь для меда
Удобней для людей с русской раскладкой
:cl:
code: /mob/living/proc/get_message_mode(message) преобразование русского символа канала в английский
add: русские префиксы в RADIO_PREFIXES
/:cl:
=> Русские префиксы для чата

code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
При любом действии, хантера становится видно на 50 процентов. перелезания через  кады/оконные рамы, винты, таскание предметов, нацепление хагеров, обезвреживание нюки...
Не знаю, не знаю..
=> При любом действии, хантера становится видно.

code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
Добавляет новый "Блессинг" гиб трупа мара за 1000 очков
https://discord.com/channels/1042907674754437140/1043327256099029082/1067934095864246333
Тут подробнее
https://user-images.githubusercontent.com/99790528/216993699-d7841b07-9f21-4ce8-9bea-b0913f767008.mp4
=> xeno gib blessing

code/modules/mob/living/carbon/xenomorph/abilities.dm
фикс бага, с быстрым строительством нестов рядом друг с другом, до начала боя.
Несты не должны строятся рядом друг с другом.
:cl:
fix: Уродск.
cl:
=> фикс бага, с быстрым строительством нестов рядом

code/_onclick/hud/xeno/xeno.dm, code/modules/mob/living/carbon/xenomorph/death.dm, code/modules/mob/living/carbon/xenomorph/life.dm
Добавляет тултипы для HUDа ксеноморфов
Делает худ ксеноморфов более понятным для новичков
:cl:
qol: Добавленны тултипы для HUDа ксеноморфов
/:cl:
=> Добавляет тултипы HUDу ксеноморфов

RUtgmc/code/RU_items.dm
Подствольный фонарик для вектора
Подствольный фонарик для вектора. Марин радость. Удар.
:cl:
add: Подствольный фонарик для вектора
:cl:
=> Подствольный фонарик для вектора

code/controllers/subsystem/points.dm, code/modules/reqs/supply.dm, tgui/packages/tgui/interfaces/Cargo.js
Добавляет маринам возможность самостоятельно одобрать свои заказы за персональные поинты.
Как их получить? Очень просто:
- 0.5 поинтов добавляется базово каждые 10 секунд
- 10% от прибыли с продаж трупов и работающих майнеров
Персональные поинты ограничены максимумом в 600 единиц, так что не забывайте периодически их тратить
В карго много вещей которые не пользуются спросом просто потому, что есть другие вещи получше, и на них жалко тратить поинты. Давая каждому марину свою, небольшую часть прибыли, они смогут покупать свои любимые вещи не забирая очки с более нужных для команды вещей.
:cl:
add: Добавил систему персональных карго поинтов
/:cl:
=> Персональные карго поинты

RUtgmc/code/RU_items.dm
-
Имба итем должен стоить дорого.
:cl:
balance: стоимость валибарды повышена с 400 до 600
/:cl:
=> Повышение стоимости валибарды

code/controllers/subsystem/points.dm
Теперь персональные поинты будут получать только: 
SQUAD_LEADER, SQUAD_SMARTGUNNER, SQUAD_CORPSMAN, SQUAD_ENGINEER, SQUAD_MARINE
Убрал базовые 0.5 поинтов за тик
Понизил % прибыли до 5%
Как-то слишком хорошо получилось, надо понерфить
:cl:
balance: Немного изменил получение персональных поинтов
/:cl:
=> Изменения персональных поинтов

code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Кинг теперь считается за правителя хайва и останавливает коллапс.
Для противодействия невероятному скилл иссуе ксенов было решено дать кингу аттирбут правителя хайва.
:cl:
balance: Кинг теперь считается за правителя хайва
/:cl:
=> Кинг теперь считается за правителя хайва

code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm, code/modules/vehicles/mecha/mecha_defense.dm
Прочность меха понижена c (900-1800) до (600-1200)
Починка меха теперь требует больше времени
Починка меха ниже 50% прочности требует пласталь
Мех всё ещё слишком танкует и слишком быстро чинится.
:cl:
balance: Нерф прочности и ремонта меха
/:cl:
=> Нерф прочности и ремонта меха

code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
Кинг теперь призывает ксеносов только со своего Z-уровня
=> king summon fix

code/__DEFINES/mode.dm, code/modules/mob/living/carbon/xenomorph/hive_datum.dm, code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm, code/modules/xenomorph/xeno_structures.dm
- Сило 800 > 600
- Кислотная турель 100 > 40
- Резиновая турель 50 > 25
- Феробашни 150 > 100
- Умные миньоны 500 > 100
- Эвобашня даёт 2 слота Т3 и 4 слота Т2 ( вместо 1 Т3 и 2 Т2)
- Феробашни имеют силу феромонов 10 вместо 5
- Генерация ляврапоинтов с сило увеличена в 2 раза с 0.035 до 0.07 за марина
80% покупок в меню благословений бесполезно, и я считаю что это плохо. Собственно, то что часто покупают (матюрки и примо) я не трогал, зато теперь появились вкусные альтернативы.
:cl:
balance: Скидки на благословления ксено
/:cl:
=> Скидки на благословления ксено

code/game/objects/machinery/nuclearbomb.dm
Перенес все хорошее
Диск кладется в руку. Небольшой рефактор.
Диски не под нюкой.
:cl:
code: Добавление balloon_alert
code: Перенос диска в руки
code: Небольшая чистка кода для большей читаемости
/:cl:
=> Апдейт нюки

code/game/objects/items/tools/maintenance_tools.dm
Фикс клика сваркой и рантайма при взрыве бака
Сварка не пропадает волшебным образом. Меньше на 1 рантайм
:cl:
del: Старый код отвечающий за поджигание сваркой
fix: Рантайм при нажатии на бак включенной сваркой
/:cl:
=> Фикс сварки

code/modules/vehicles/mecha/mecha_defense.dm
=> Фикс починки меха

code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
Хайвмайнд больше не сможет строить блессинги в гост форме
=> Фикс строительства блессингов хайвмайнда

code/__DEFINES/mode.dm
8 лявра поинтов в минуту это конечно весело, но эксперимент пора заканчивать
=> Откат баффа сило

code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm, code/modules/vehicles/mecha/mecha_defense.dm
Чот он стал слишком быстро умирать, возможно я перестарался
=> Откат нерфа ХП меха

code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
Боевые способности хантера не сильно увеличит, но позволит иногда делать весёлые вещи. Тем более, что марины своих легко могут опознать.
=> Disguise хантера теперь работает и на людей

code/__DEFINES/is_helpers.dm, code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
Кинг теперь может купить примо
=> Кинг может купить примо

code/modules/reqs/supplypacks.dm
Добавляет слаги на MBX-900 в карго.
=> Слаги на MBX-900 в карго

code/datums/loadout/loadout.dm
Теперь можно взять 1 предмет из лодаута
Если потеряно оружие или броня теперь можно взять только их из лодаута
:cl:
add: Выдача предмета при нажатии на слот в лодауте 
/:cl:
=> Апдейт лодаута

code/datums/components/_component.dm, code/datums/components/ai.dm, code/modules/ai/ai_behaviors/ai_behavior.dm
Фикс ИИ мобов после азиза
ИИ мобы с спавнеров идут на метку
:cl:
code: Замена length_char на length
/:cl:
=> Фикс спавнеров

code/__DEFINES/mobs.dm, code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
Возвращает градацию инвиза и убирает полную невидимость
Теперь у хантера будет:
- 99,5% инвиза неподвижным
- 98% инвиза при ходьбе
- 95% инвиза при беге
полный инвиз всегда и везде - хуета
:cl:
balance: Нерф полного инвиза хантера
/:cl:
=> Нерф полного инвиза хантера

code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
Абилка увеличивает разброс у пушки, уменьшает точность стрельбы. Плюс накладывает замедление на несколько тиков.
=> Бафф off-guard'a Кинга

code/game/objects/items/storage/belt.dm, code/game/objects/items/storage/pouch.dm, code/game/objects/structures/stool_bed_chair_nest/bed.dm, code/modules/clothing/modular_armor/attachments/storage.dm
Медицинское говно лезет в медицинское говно
Родя будет доволен
Блундир будет доволен
Пинцет лезет в лайфсейвер и риг
Пинцет лезет в медкит
Эвак теперь лезет в мед модуль на броню
Маяк эвака теперь размером с другие маяки
:cl:
balance: rebalanced some med item sizes 
/:cl:
=> Пинцетная братва

code/modules/xenomorph/xeno_structures.dm
Сила феромонов феробашен понижена с 10 до 8
=> Феробашни 10 > 8

code/modules/vehicles/mecha/mecha_defense.dm
Фикс мгновенной починки меха пласталью
=> Фикс мгновенной починки меха пласталью

code/datums/status_effects/xeno_buffs.dm, code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm, code/modules/mob/living/carbon/xenomorph/castes/gorger/castedatum_gorger.dm
- Добавил визуальный эффект хилу от Feast
- Drain и Carnage теперь сосут 30 крови вместо 10
- Увеличено сосание плазмы от Drain и Carnage
- Добавлен пассивный реген плазмы с капом в 10%
- Psychic Link теперь не требует лежать на месте, КД уменьшено с 50 до 15 сек
=> Баффы горжера часть 2

_maps/shuttles/tgs_bigbury.dmm
Фикс левой двери на бигбури
Марины могут открывать левую дверь
:cl:
fix: Айди левой кнопки
/:cl:
=> Фикс левой двери

code/modules/projectiles/projectile.dm
Фикс нуля в логе попадании пули. Изменена немного логика. Теперь существам без клиента не будут выводится логи.
Аллах так сказал
:cl:
fix: Нуля из за отсутствия клиента
code: Логи не создаются мобам без клиента
/:cl:
=> Фикс логов пуль

code/_onclick/hud/screen_objects/menu_text_objects.dm, code/_onclick/hud/screen_objects/screen_objects.dm, code/controllers/subsystem/greyscale.dm, code/controllers/subsystem/job.dm, code/controllers/subsystem/minimaps.dm, code/datums/components/autofire.dm, code/datums/status_effects/debuffs.dm, code/game/objects/items/motion_detector.dm, code/game/objects/items/radio/headset.dm, code/game/objects/items/weapons/blades.dm, code/modules/mob/dead/observer/orbit.dm, code/modules/mob/inventory.dm, code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm, code/modules/organs/organ_internal.dm
Фикс целой кучи нулей.
Чище логи. Серверу легче жить без нулл референсов.
:cl:
fix: много где проверка на нул
/:cl:
=> Фикс нулей

code/datums/elements/deployable_item.dm
Фиксит баг неправильного спавна деплой объектов. Деплой теперь на ПРАВУЮ КНОПКУ МЫШИ
Телепорты работают и тд. Дальше сами придумаете
:cl:
code: Деплой по сигналу предмета COMSIG_ITEM_AFTERATTACK_ALTERNATE
del: Глобальный список деплоев
/:cl:
=> Фикс деплоев

code/datums/wires/autolathe.dm, code/game/objects/items/jetpack.dm, code/game/objects/machinery/computer/nuke_disk_generator.dm, code/game/objects/structures/droppod.dm, code/modules/mob/living/carbon/xenomorph/attack_alien.dm, code/modules/mob/living/carbon/xenomorph/castes/panther/abilities_panther.dm, code/modules/mob/living/carbon/xenomorph/egg.dm
Изменение проков до стандарта 515 версии
Работает игра
:cl:
code: замена .proc на TYPE_PROC_REF и PROC_REF
/:cl:
=> Обновление до 515

code/modules/keybindings/setup.dm
Изменение вкладки верба Исправить раскладку на ООС
Минус вкладка
:cl:
code: вкладка верба с Special verbs на ООС
/:cl:
=> Изменение вкладки верба

code/__DEFINES/action.dm
Теперь варриор будет видеть какая абилка у него активна
=> Фикс иконок варриора

code/datums/elements/deployable_item.dm, code/modules/projectiles/gun_attachables.dm
Небольшая чистка деплоев. Теперь деплои всегда ставятся из-за того что не ожидается сигнал на взятие в руки. Баг фикс адона турели на оружие.
Нет багов лагов
:cl:
del: Повторяющееся удаление элемента из оружия при снятии адона турели
del: Убраны сигналы эквип и анэквип из деплоев
/:cl:
=> Небольшая чистка

code/game/objects/machinery/mortar.dm, code/game/objects/structures/teleporter.dm, code/modules/projectiles/gun_system.dm, code/modules/projectiles/guns/mounted.dm
Изменение описаний деплоев
Игруны не жалуются
:cl:
code: изменено описание деплоев
/:cl:
=> Фикс описания деплоев

code/game/objects/items/motion_detector.dm
Сканер показывает всех независимо от движения
Сканер все еще говно
:cl:
del: проверку на движение
/:cl:
=> Лютый ап сканера

code/modules/projectiles/projectile.dm
Убираем создание красного варенья на экране при попадании пули
В теории пофиксит ксенолаг
:cl:
code: flash_weak_pain() больше не вызывается в /mob/living/bullet_act
/:cl:
=> Тестовый фикс пеин худа

_maps/map_files/generic/Admin_Level.dmm, code/modules/security_levels/keycard_authentication.dm
Кнопка для поднятия кода неразрушаема, в вальхале нет карты капитана
В вальхале меньше приколов, кнопки кода не дрочат
:cl:
code: кнопка кода имеет флаг INDESTRUCTIBLE
del: карту капитана из вальхалы
/:cl:
=> Кнопка и карта

code/datums/gamemodes/crash.dm, code/modules/xenomorph/xeno_structures.dm
Сило на краше и его тоннели теперь INDESTRUCTIBLE
Не ломают абузами сило
:cl:
add: краш вариацию сила
code: если сило неразрушимо, то его тоннель тоже
/:cl:
=> Неуничтожимое сило краша

code/datums/gamemodes/crash.dm, code/datums/jobs/job/marines.dm, code/datums/jobs/job/shipside.dm
СЛ, ФК, Синт дают больше поинтов для ксено популяции
4 сла не будут попускать 1 ксена, а 2ух
:cl:
add: краш версии джобок синта, сл, фк
/:cl:
=> Повышение цены на краше

code/datums/gamemodes/crash.dm, code/datums/jobs/job/marines.dm, code/datums/jobs/job/shipside.dm
Общее повышение ролей сла, синта, фк ибо не лень переписывать половину игры из за краша
Больше ксенов за сильные роли
:cl:
code: сл, синт, фк LARVA_POINTS_STRONG
del: краш версии ролей
/:cl:
=> Общее повышение цены ролей

code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm, code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Крашер и вориор не могут закидывать в туман
Минус еще 1 распрыжка и хитрость
:cl:
code: проверка на тайл ксена в способности cresttoss и toss
/:cl:
=> Фикс броска за туман

code/game/objects/machinery/nuclearbomb.dm, code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Нюку нельзя телепортировать через порталы. Нельзя телепортировать в туман людей и тд
Еще 1 хитрость пофикшена
:cl:
code: у нюки теперь флаг PORTAL_IMMUNE
code: проверка на тайл ксена в способности blink
/:cl:
=> Фикс телепорта в туман

code/modules/client/preferences_ui.dm
Фикс отсутствия кнопки выбора разрешений
Можно выбрать разрешение экрана
:cl:
code: вернул присвоение значения кнопке
/:cl:
=> Фикс кнопки выбора разрешения

code/modules/mob/living/carbon/xenomorph/abilities.dm
Не позволяет использовать инста застройку до створок рядом с людьми
Сурвы смогут жить на 1.5 секунд больше
:cl:
code: проверка в инста застройке на живых людей с игроком
/:cl:
=> Нерф инста застройки до створок

code/modules/mob/living/carbon/xenomorph/abilities.dm
Инста застройка теперь только на левую кнопку мыши
Позволяет использовать обычную застройку вместе с инста застройкой
:cl:
code: проверка инпута при клике постройкой
code: проверка существования тайла при инста застройке
/:cl:
=> Доработка инста застройки

code/datums/actions/xeno_action.dm
Исправляет баг у примо война, когда отображение активной "комбы" было вечной.
=> warrior_primo_fix

code/game/objects/machinery/adv_med.dm
Багфикс нула при отсутствии человека внутри и открытом интерфейсе сканера
Меньше нулов
:cl:
code: проверка на наличие человека внутри
/:cl:
=> Фикс мед сканера

code/modules/mob/living/blood.dm
Квикклот больше не позволяет бесконечно стакать кровь
Нету маринов 500% крови
:cl:
code: больше не используется метод кровотечения для удаления лишней крови
/:cl:
=> Фикс количества крови

code/modules/mob/living/carbon/xenomorph/xenoattacks.dm
Квина может шовать всех.
Лидеры могут шовать всех, кроме квины и других лидеров.
Кинг и шрика могут шовать всех, кроме квины и лидеров.
Людей шовать нельзя.
Другой хайв шовать нельзя.
=> Ксены могут сбивать друг друга с ног

code/game/objects/machinery/mortar.dm
orig pr https://github.com/tgstation/TerraGov-Marine-Corps/pull/12622
100% ксенобаф
:cl:
fix: mortar sound
/:cl:
=> fix mortar sound

code/modules/mob/living/carbon/human/human_attackhand.dm
orig pr 
https://github.com/tgstation/TerraGov-Marine-Corps/pull/12605
100% маринбаф
:cl:
add: When you check yourself for wounds, you can see the dirt you've accumulated. Mostly only matters for surgeons.
/:cl:
=> Adds self germ check 

code/game/turfs/turf.dm
orig pr
https://github.com/tgstation/TerraGov-Marine-Corps/pull/12702
idk
:cl:
fix: Acid on walls gets deleted if the wall gets deleted
/:cl:
=> fix acid on wall

code/game/objects/structures/orbital_cannon.dm
orig PR 
https://github.com/tgstation/TerraGov-Marine-Corps/pull/12135
100% маринбаф
Тгаз ОБ будет использоваться в игре
:cl:
fix: Plasma OB will now hit the lased position instead of going off in the OB room
/:cl:
=> Fix Tgas OB

code/_onclick/item_attack.dm, code/game/objects/structures/inflatable.dm
orig pr
https://github.com/tgstation/TerraGov-Marine-Corps/pull/12657
:cl:
code: Some minor code cleanup
/:cl:
=> minor code fixes 

code/modules/projectiles/ammo_datums.dm
Корректировка и так убитых боеприпасов в игре на играбельные значения между предпоследним и последним нерфом: https://github.com/tgstation/TerraGov-Marine-Corps/pull/9253 и https://github.com/tgstation/TerraGov-Marine-Corps/pull/9388. 
Дрожание экрана при попадании и стаггер добавляться не будет, так как делает их слишком сильными боеприпасами даже для карго.
Добавлено: старое пробитие с отталкиванием.
"Пронзание" оставлено.
После ослабления ударных боеприпасов они стали намного хуже обычных из-за потерь их основных свойств, таких как: пробитие и отбрасывания, хоть и после этого было добавлено "пронзание" - это не сделало их лучше.
Сейчас стоимость боеприпасов в два раза дороже за, по сути, худшее качество.
:cl:
balance: add knockback and high penetration
:cl:
=> Корректировка ударных боеприпасов

code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
Убирает 15 дополнительного чистого урона у хантера.
=> hunter damage nerf

code/controllers/subsystem/silo.dm
Максимальный коэффициент динмического скейлинга сило понижен с 2 до 1.25
=> Нерф динамического скейлинга сило

code/controllers/subsystem/silo.dm
Чот работает не так как надо и я хз как починить. Пока что уберу.
=> Удаление динамического скейлинга

code/modules/mob/living/carbon/xenomorph/abilities.dm
bug fix
100% маринбаф
:cl:
fix: xeno cant spit without cd
/:cl:
=> Xeno_spit_fix

code/datums/jobs/access.dm, code/datums/jobs/job/shipside.dm
у синтов теперь 10 рангов
Mk.1 всё также до 10 часов
Mk.2 от 10 до 50
Mk.3 от 50 до 100
Mk.4 от 100 до 150
Mk.5 от 150 до 200
и так далее
Mk.10 от 1000 часов
у синтов больше званий
:cl:
add: Added rank to synth, now it have 10 ranks
/:cl:
=> Теперь у синтов больше рангов V2

code/modules/xenomorph/xeno_structures.dm
Уменьшает силу феро таверов с 8 до 6, как у кинга.
Марин слабый, Ксенос сильный, надо исправлять.
=> pherotower nerf 8->6

code/modules/projectiles/guns/specialist.dm, code/modules/projectiles/magazines/specialist.dm, code/modules/reqs/supplypacks.dm
+ У 85 сг теперь 2000 патронов в павер паке максимум. (в начале игры/при покупке павер пака их тоже 2000)
+ Добавил павер пак за 150 в карго
=> SG 85 buf + powerpack в карго

code/datums/components/suit_autodoc.dm
Спустя  4 месяца я вспомнил..... 🤔
=> Удаление лишней кнопки в автодоке

code/modules/clothing/modular_armor/attachments.dm
наныли на фикс пкм при покраске
фиксы багов
+стиль
:cl:
fix: change call proc on PROC_REF
/:cl:
=> fix_rmb_paint

code/_onclick/hud/screen_objects/screen_objects.dm, code/modules/projectiles/gun_system.dm
orig pr - https://github.com/tgstation/TerraGov-Marine-Corps/pull/12761
ыыы!!!!
100% маринбафф
:cl:
add: Clicking on a UI box will click on whatever is inside the box.
del: Guns are no longer opaque
/:cl:
=> порт фикса больших спрайтов

code/datums/jobs/job/shipside.dm
Ну что же, томат проебал своего лейтенанта с обновлением базы данных, пришло время нового фарма часиков до майора? 
Два новых звания 
Лейтенант на 150 часов и Майор на 200 часов.
Напоминаю, я набил только 130 часиков, так что все впереди.
Уточнение забыл, раньше у нас был максимум Младший лейтенант.
=> Новые звание пилоту

code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
Возвращает радиальное меню Майнду
:cl:
qol: radial menu for HM
/:cl:
=> Hivemind radial menu

code/__HELPERS/ai.dm
миньоны не стукают нестированных больше. Да и они им вообще не интересны. Пока те не выберутся с неста.
100% ксенобаф
:cl:
fix: fixed minions attack nest people
/:cl:
=> fix ai xeno attack nest people

code/modules/projectiles/sentries.dm
Вроты получают "вроты"! ба-да-бум-тссс
теперь вроты не могут забанишить туррели
100% маринбаф
:cl:
add: add banish_immune to turrets
/:cl:
=> The Great Nerf Wraith

code/modules/mob/living/carbon/xenomorph/life.dm
Сломанная механика и неприятная, убираю.
=> [e] Xeno Pain Revert

code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
**BOILER**
> Немного увеличена скорость рута и кулдаун побега. Бойлеры почти неиспользуемы из-за огромных неудобств игры на них.
- [ _Root_ ] time to root/unroot = **3 —> 2**
- [ _Dump Acid_ ] cooldown = **230 —> 180**
=> [e] Boiler Tweak

code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
**SHRIKE**
> Увеличен кулдаун примо способности, комбо из её способностей не оставляет шансов морпеху.
- [ _Psychic Grab_ ] cooldown = **12 —> 30** SECONDS
=> [e] Shrike Tweak

code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm, code/modules/vehicles/mecha/mecha_defense.dm, tgui/packages/tgui/interfaces/MechVendor/MechAssembly.tsx
Абуз с групповой починкой меха плассталью закрыт. 
Буллет армор меха 400% -> 75%
Лазер армор меха 400% -> 75%
Бомб армор меха 200% -> 50%
В консоли мехвода буллет армор теперь показывает буллет армор, а не мили армор
Меньше багов.
:cl:
balance: change mecha armor
fix: fixed a few typo
/:cl:
=> Some mech fix

code/modules/mob/login.dm
Disconnected DNR fix
100% маринбаф
в связи с последними апдейтами дед_стейтов, это нам надо
:cl:
fix: Disconnected DNR fix
/:cl:
=> Disconnected DNR fix

code/modules/instruments/stationary.dm
Дохуя важное и полезное пиано работает
100%маринбаф
:cl:
fix: fixed a little flag for a big piano and ui works now
/:cl:
=> Big piano fix

code/modules/admin/topic.dm, code/modules/mob/living/carbon/xenomorph/hive_datum.dm, tgui/packages/tgui-panel/chat/constants.js, tgui/packages/tgui-panel/styles/goon/chat-dark.scss, tgui/packages/tgui-panel/styles/goon/chat-light.scss
изменены анонсы о банише ксено
админы могут отклонить баниш ксено
пофиксил возможность квины банишить ксено без причины
квина банишит ксено, а админ нажимает кнопку анбаниш:
квина банишит-дебанишит ксено:
100%админбаф
:cl:
add: add chat-button unbanish xeno
fix: queen no longer can banish xeno with no reason
change; banish announce
/:cl:
=> ADMIN GET THE POWER OF UN-BANISH

code/_onclick/hud/xeno/xeno.dm
Наименование решил не убирать как у хп худа, так как для новичков может быть не совсем понятно что это.
=> Deletes useless description of plasma xeno hud.

RUtgmc/code/clown.dm, RUtgmc/code/militarypolice.dm, code/datums/jobs/job/marines.dm, code/datums/jobs/job/shipside.dm, code/datums/jobs/job/sonsofmars.dm, code/datums/jobs/job/survivor.dm, code/datums/jobs/job/xenomorph.dm
Не нужно копаться в коде чтобы узнать когда сможешь поиграть за кого-то? Возможно я конечно ошибаюсь и где-то это уже написано, но и это не помешает.
:cl:
qol: Требования для разблокировки разных работ теперь можно посмотреть в описании работы, до этого на большинстве работок было просто "Starting Role".
/:cl:
=> Corrects Unlock Requirements for jobs that have them set.

code/_onclick/hud/ghost.dm
Если нажимал на крестик то тебя засовывало назад в тело.
=> Reenter corpse X fix.

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Дупликаты труб генерируют кучу текста и мешают когда запускаешь локалку.
=> Deletes few duplicate pipes on the Pillar of Spring ship.

code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
Ограничивает количество активных сило до 1 шт.
=> silo limit to 1

code/game/objects/structures/droppod.dm
Фикс всевидящего ока дропподов
=> droppod camera fix

code/datums/gamemodes/nuclear_war.dm
Теперь подрыв нюки на земле будет мажор победой маринов (вместо минора как было ранее)
=> nuke major

code/modules/mob/living/carbon/xenomorph/abilities.dm
Так сообщение будет ориентироваться на название самой абилки.
=> Corrects message of Ozelomyn Sting cooldown finish.

code/modules/mob/living/carbon/xenomorph/life.dm
Увеличивает реген сандера на траве в 2.5 раза, и на белой траве в 2.5 раза
=> sunder heal buff

code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
Рут и анрут теперь занимают по 0.5 секунды
=> faster boiler root

code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
Долгожданный бафф врота на 1 (2) урона
=> wraith buff

code/modules/xenomorph/xeno_structures.dm
Бафф здоровья ксено туннелей. Используйте взрывчатку
=> xeno tunnel buff

code/datums/gamemodes/distress.dm, code/datums/gamemodes/nuclear_war.dm
=> silo scaling nerf

code/__DEFINES/loadout.dm
Читать название пра
В вендоре инженера есть оверклок и реинфорсмент апгрейды, но нет автомайнера, опущение.
Инже бафф 100%
:cl:
add: Added mining computer in engineer point vendor
/:cl:
=> Mining computer in engineer point vendor

code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
Я скилл ишью и здох от этого.
По логике, если ты не можешь лечь отдыхать когда в стойке, то и вставать в стойку когда отдыхаешь ты не должен.
=> Restricts boiler from rooting while resting.

code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm, code/modules/xenomorph/xeno_structures.dm
Лимит на 3 активных феровышки, цена повышена до 200
=> pherotower nerf and limit

code/datums/jobs/job/fallen.dm
Таким образом `do not grief,` не будет слитно с `do not try`
=> Adds spacebar to vallhalla warning message.

code/datums/jobs/squads.dm, code/game/objects/machinery/overwatch.dm
:cl:
fix: Foreign squad transfer fix
/:cl:
=> Marines transfer hotfix

_maps/map_files/Sulaco/TGS_Sulaco.dmm
Меньше ошибок при загрузке карты.
=> Deletes duplicate pipes from sulaco.

_maps/map_files/Minerva/TGS_Minerva.dmm
Помимо дубликатов труб, в крио также были не совсем правильно подсоединены трубы.
=> Deletes duplicate pipes from Minerva.

code/game/objects/items/storage/belt.dm
Там было всего 5 магазинов, хотя вмещается 6.
=> Adds missing magazine to powder monkey ammo belt.

code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
Понижена стоимость ловушек и спавна хаггеров
=> carrier buff
