- code/datums/view.dm
- code/game/objects/items.dm
- code/game/objects/items/binoculars.dm
- code/modules/clothing/modular_armor/attachments/modules.dm
- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
- code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
- code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
- code/modules/projectiles/gun_attachables.dm
- code/modules/projectiles/guns/specialist.dm
- config/config.txt
Исправлен пролаг при использовании прицелов, биноклей и т.д. с включенным Widescreen. Widescreen теперь 21х15 из-за соотношений сторон 1,4:1. При старом 19х15 (1,26:1) невозможно без изменений окна увеличивать/уменьшать обзор.
Из-за того что соотношение сторон теперь 1,4:1 увеличивать обзор стоит на числа кратные 5 для того чтобы не изменять окно в Widescreen. Квадратный режим работает так же без изменений.
Зум можно нормально использовать не только в дефолтном окне.
:cl:
add: При изменении размера окна происходит попытка сохранить соотношение сторон
code: Дефолтный зум 7>5
code: Зум биноклей 12>15
code: Зум госта 26>25
code: Зум квины 9>10
code: Зум бойлера 8>10
code: Убрал ненужные вычисления при зуме ксеноморфов
code: Зум дефолтного прицела 2>5
code: Зум оптики 12>10
config: Widescreen …
> Фикс зума с вайдскрином

- code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Удаление эффектов тряски и помутнения для самого Равы при нажатии ярости (другие ксено или мары всё ещё будут их получать)
При супер рейдже, Рава получает фильтр 'жажды крови' который до этого был только у Горгера (вроде бы)
Улучшение 'качества жизни'
Это просто удобно и приятно
Логично что эффект 'ааа, он так громко крикнул' должны получать морпехи или хотя бы другие ксеноморфы, но никак не сам тот кто 'громко крикнул'
Теперь рава в самый важный момент нажатия супер ярости/ярости не будет теряться как слёпой котёнок из за трясущегося экрана, а впиваться в плоть морпехам, получая отхил.
:cl:
add: Красоту.
add: Кайф.
del: Многие скил ишуй моменты с равами.
:cl:
> Тот же фильтр у равы, чистая история комитов. Удар.

- code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
Дал способности крашера "Stomp" 100 пробивания 
https://user-images.githubusercontent.com/99790528/212540035-7117aa3b-ec18-4a9c-895e-cb5292c2b9e8.mp4
Способность крашера "Stomp" имеет особенность, а именно, если стоять на цели - она нанесёт в два раза больше урона
Но к сожалению из за особенности её кода(нанесение малого количества урона но всему телу), броня полностью убирала двойной урон по цели, что полностью лишает смысла эту часть способности.
Теперь нет.
:cl:
fix: Не рабочая часть способности "Stomp" теперь работает.
/:cl:
> Crusher stomp fix

- code/__DEFINES/mobs.dm
- code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
Теперь хантер, после некоторого времени активации способности, становится полностью невидимым.
трата плазмы в невидимости уменьшена
при ходьбе - до 1
при беге - до 2
Время до возможности сделать скрытую атаку, уменьшено с 3 до 2. (всё ещё есть 5 секунд кд у невидимости, т.е время между этими ударами суммарно 7 секунд)
Дыра в линейки Руня -> Хантер-> Рава. Будет частично закрыта. Теперь не будет ощущения что ты просто ждёшь эво очки и слот, пока растёшь на хантере.
:cl:
add: Воровство предметов прямо на глазах у маров.
add: Толкание маров в застройку из невидимости. (хантера всё ещё видно через шифт+пкм, и слышно на сенсорах)
del: Полная бесполезность невидимости / хантера без примо.
:cl:
> Hunter apha stealth increase 

- code/game/objects/structures/stool_bed_chair_nest/xeno_nest.dm
Таймер на запрет бакла теперь работает как задумано
Таймер увеличен с 5 до 15 секунд 
Багфикс
:cl:
fix: Nest timer bugfix
/:cl:
> Fix nest timer

- code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
Теперь когда у щита хп меньше некого порога (300, 175, 125). Его прозрачность повышается.
Так же. на последней стадии прозрачности, для варлока всплывает сообщение "Our shield is almost broken!" (если 125 хп не снимаются за выстрел, starege)
Более очевидная работа щита, как для варлока, так и для его противников.
:cl:
add: Прозрачность игрового процесса.
:cl:
> Прозрачность щита, при маленьком остатке прочности.

- RUtgmc/code/RU_items.dm
т500 с одной руке стал стрелять точнее (hand gun же все дела)
компенсатор делает стрельбу с одной руки немного точнее
приклад немного повышает урон ревика в мили
сам ревик стал тяжелее и наносит больше урона в мили (убраны чересчур заниженные характеристики по сравнению с другим оружием)
не знаю
:cl:
balance: t500 accuracy buff
/:cl:
> Поднятие точности т500 при стрельбе с одной руки

- code/datums/gamemodes/distress.dm
После баффа блессингов оказалось что у ксенов стало меньше псипоинтов...
Этот ПР возвращает 2000 псипоинтов.
> Фикс псипоинтов

- code/game/objects/items/storage/bible.dm
- code/modules/client/preferences_gear.dm
Почему-то количество слотов в Библии уменьшилось с 7 до 1, поэтому пострадал люксовый Коран из лодаутов
Возвращаю ему и только ему 7 слотов, поскольку это эксклюзивный предмет для лодаута, который так был задуман
Добавил в лодаут б19
откат нерфа маринов
:cl:
add: b19 armor in gear for 6 points
fix: fix gear koran slots reduction
/:cl:
> Откат нерфа Корана

- code/modules/projectiles/guns/pistols.dm
Подствольный фонарик у плазмапистола
На плазмач лезет обычный фонарик
На плазмач лезут подстволы
На плазмач должен лезть подствольный фонарь, но оффы забыли его добавить
Исправляем
:cl:
fix: plasma pistol cant hold under flashlight
/:cl:
> Подствольный фонарик у плазмапистола

- code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Добавляет 2 новых грейда феромонов в панель.
- Extreme: от 6.0 до 7.9 (уровень эншент кинга)
- Superior: от 8 и выше (уровнь феробашен)
Сделано для большей информативности, что бы игрок видел когда он выходит/выходит из зоны действия сильнейших феромонов.
> 2 новых грейда феромонов в панели

- code/__DEFINES/objects.dm
- code/datums/components/suit_autodoc.dm
- code/modules/clothing/modular_armor/attachments/modules.dm
1.  Валькирия теперь не замедляет
2. Уменьшен и значительно увеличен диапазон настройки триггеров
50-150>>20-300
Это позволит тоньше настраивать и костыльно отключать ввод трико и трамадола, что позволит спокойно использовать в случае надобности парацетамол и рейталин. (да, я блять просто не смог сделать кнопки on и off)
3. Добавлены кнопки -100 и +100
4.  2 и 3 пункт относятся также к автомедику б18
> НЕРЕАЛЬНЫЙ (юбилейный сотый пр) бафф валькирии и б18

- code/datums/status_effects/xeno_buffs.dm
- code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm
Баффы и удобства для бесполезной касты
- Feast теперь действует на всех ксеноморфов в радиусе 4 клеток, КД уменьшено с 180 до 30 сек
- Drain и Carnage сосут настоящую кровь у морпехов
- Transfusion не требует стоять на месте, дальность увеличена с 2 до 3 клеток
> Баффы горжера

- code/game/objects/items/weapons/weapon.dm
Маленькая фича для большей кастомизации своей пушки, или меча, или копья, или щита, или даже турели.
Сменить имя можно ручкой.
> Возможность переименовать оружие.

- code/__DEFINES/loadout.dm
- code/datums/loadout/loadout_helper.dm
- code/game/objects/machinery/vending/marine_vending.dm
- code/game/objects/machinery/vending/new_marine_vendors.dm
- code/game/objects/machinery/vending/vending.dm
Фикс лодаут вендора в вальхале. Теперь он выдает все предметы из лодаута. Фикс ксенаута в лодауте. Он теперь выдается нормально всегда.
Это должно было быть так
:cl:
code: проверка на фракцию VALHALLA и режим игры при выдаче лодаута или венда предмета
code: вендоры вальхалы теперь имеют фракцию VALHALLA
fix: лист вендоров вальхалы
/:cl:
> Фикс вендоров вальхалы

- _maps/shuttles/tgs_bigbury.dmm
- _maps/shuttles/tgs_canterbury.dmm
- code/__DEFINES/factions.dm
- code/__DEFINES/loadout.dm
- code/game/objects/machinery/vending/loadout_vendor.dm
Теперь вендоры лодаутов будут давать оружие из оружейного вендора краша, а не обычного
Не берут через абуз миномет, трубу и тд
:cl:
add: новая фракция FACTION_NEUTRAL_CRASH
add: вариация лодаут вендора для краша
add: вендоры в список фракции FACTION_NEUTRAL_CRASH
code: заменена лодаут вендоров на кораблях краша
/:cl:
> Фикс лодаут вендора краша

- code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
Бафф Дефендера!
Превращаем бесполезный скилл "Regenerate Skin" в, возможно, полезный! 
Теперь скилл стоит не "дохуя плазмы"(160), а "дохуя плазмы разделить на 2"(80)
Больше вариативности игры на дефендоре
скилл, который используется раз в полгода на поле новичками, или же раз в минуту-две дефендерами, которые хиллятся на траве вне боя - теперь возможно будет использоваться чаще
:cl:
balance: rebalanced plasma cost of "Regenerate Skin" skill
/:cl:
> Defender Lives Matter!

- code/controllers/subsystem/silo.dm
Сейчас спавн лярв от сило зависит исключительно от количества живых маринов на земле.
Данный ПР добавляет модификатор спавна, зависящий от соотношения живых ксенов к живым маринам.
Модификатор варьируется от 10% до 200%.
Модификатор равен 100% при соотношении 2,5 к 1 (например 40 маринов на 16 ксенов).
Сделано для того, что-бы ксены не получали слишком большого преимущества при долгом паритете, но в то-же время быстрее восстанавливались от крупных потерь.
> Динамическое изменение скейлинга сило

- RUtgmc/code/RU_items.dm
T25 теперь имеет пулю.
https://github.com/Cosmic-Overlord/TerraGov-Marine-Corps/assets/116975250/a4d3eb37-275c-4915-88d9-563010dfad1c
https://github.com/Cosmic-Overlord/TerraGov-Marine-Corps/assets/116975250/c910f582-ce27-48e2-bb11-a877365d151e
:cl:
fix: fixed t25 bullet
:cl:
> Фикс пули т25

- code/modules/projectiles/gun_system.dm
- code/modules/projectiles/magazines/sentries.dm
orig pr https://github.com/tgstation/TerraGov-Marine-Corps/pull/12646
маринбаф 100%
теперь мне не придётся тащить в руках деревянный ящик из под сентри, но без сентри и с патронами :catRose:
:cl:
balance: Sentry ammo is now sentry sized (Normal)
/:cl:
> fix sentry ammo size

- code/game/objects/machinery/cryopod.dm
- code/modules/shuttle/escape_pod.dm
orig pr
https://github.com/tgstation/TerraGov-Marine-Corps/pull/12715#issue-1665979895
не будет смешного
:cl:
fix: Cancelling the channel to enter a cryo pod on the evac shuttle will no longer ghost you.
/:cl:
> Fix evac pod ghost

- code/game/objects/items/reagent_containers/hypospray.dm
Теперь объекту показывает имя субъекта использовавшего гипоспрей и автоинжектор. Нужная фича в время отсутствия администрации, которая поможет найти виновного.
> Предотвращение гриферства гипоспреями и автоинжекторами

- code/controllers/subsystem/points.dm
- code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Пока что все цифры тестовые.
Прирост - 10%
Лимит - 100
Матюрити и эволв по 30, примо по 50
Покупать во вкладке "Alien"
Ещё увеличил прирост персональных поинтов маринам с 5% до 7,5%
> Персональные пси поинты для ксенов

- code/controllers/subsystem/points.dm
- code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Уменьшение начисления пси поинтов с 0.1 до 0.016 в секунду (2 в минуту).
Так же понизил цену эво апгрейда с 30 до 20 
Сейчас персональные поинты слишком сильны.
> personal pry point nerf.

- code/modules/mob/living/carbon/xenomorph/castes/crusher/crusher.dm
- code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
- code/modules/projectiles/projectile.dm
У ксено появился порез урона проджектайлов, если они повёрнуты к ним мордой.
Что мы имеем
Если крашер повёрнут лицом к проджектайлу (на мили не работает, на ножи, гранаты и т.д не работает)
И между ними есть хотя бы одна клетка
У проджекта урон режется на 70 процентов, до начала работы брони
Эти проценты уменьшаются от сандера.
Квина имеет деф 50 процентов
Уменьшается от сандера (и остальные условия)
Если какой либо ксенос находится в чарже, он блокирует 20 процентов урона, до работы брони
Уменьшается от сандера ( не нужно быть повёрнутым головой к пули, но остальные условия работают)
> Front armor xeno

- code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
Уменьшил перезарядку примо с 60 до 20.
Cчитаю что 60 просто не адекватная цифра, учитывая механизм реализации способности и кд остальных способностей раннера. Офы вообще любят ставить сумасшедшие кд, как 300 для гранаты шрики.
Теперь после окончания способности, украденная вещь, автоматически берётся в пул, без виндапа.
Cчитаю что это должно было быть в способности изначально, если бы тогда ксены могли пулить. Теперь они могут, пора добавлять.
Добавил в список возможных украденных предметов шлем, на третью позицию (сначала активный предмет в руках, затем SLOT_S_STORE (левый слот, куда суются пушки) и потом шлем).
Настоящий баф, который делает смешную способность более смешной, опасной только если мар успел потерять снаряжение дважды до этого.
> Runner primo buf

- code/game/objects/structures/dropship_ammo.dm
Да, нам это нужно, да без этого никак, потому что пулемет КАС все еще юзлес, а ракеты все еще дорогие, спидмерж оформляйте.
Теперь пули у стандартной ленты летят не 6, а 4 секунды, количество патрон увеличилось с 200 до 260 (плюс 3 клика), стоимость упала с 75 до 50 поинтов.
> Бафф стандартной пулеметной ленты КАС

- code/controllers/subsystem/points.dm
Теперь в минуту будет капать не 18, а 26 поитов в фабрикатор авиации, причина тому: Вырезание карточек в карго, большие цены на ракеты и их малая эффективность.
> Больше поинтов КАСу

- _maps/map_files/Minerva/TGS_Minerva.dmm
- _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
- _maps/map_files/Sulaco/TGS_Sulaco.dmm
- _maps/map_files/Talos/TGS_Talos.dmm
- _maps/map_files/Theseus/TGS_Theseus.dmm
- _maps/map_files/debugdalus/tgs_debugdalus.dmm
- code/game/objects/structures/dropship_equipment.dm
- code/modules/projectiles/guns/mounted.dm
- code/modules/projectiles/mounted.dm
- code/modules/reqs/supplypacks.dm
Порт пра номер раз https://github.com/tgstation/TerraGov-Marine-Corps/pull/13411, номер двас https://github.com/tgstation/TerraGov-Marine-Corps/pull/13511 и номер трес https://github.com/tgstation/TerraGov-Marine-Corps/pull/13513.
Фикс от Блундира конечно тоже работал, правда только на базовый пулеметик, но у нас все равно другие пушки только Антис щупал.
Код стал лучше, пофиксилось несколько багов
:cl:
add: Readded the mounted nest minigun back to req
fix: Fixed mounted nest dropship equipment not letting you mount it
code: Refactored mounted nest dropship equipment to use inheritance
balance: Mounted guns have normalised bullet, laser and energy armor
balance: Mounted guns are dense when mounted again. Crushers rejoice
/:cl:
> Fix tadpole gun (for real this time)

- code/game/objects/items/embedding.dm
- code/modules/mob/living/carbon/human/human_defense.dm
пофикшены дюпы мили оружия
большие мили палки больше не будут застревать в бедных хуманах при бросках
пофикшен рантайм, появляющися после самостоятельного вытаскивания из своей жопы мили палок
100% предбаф
:cl:
fix: no dup mele weapon
fix: runtime\bug, proc dont have parametrs
add: check on w_class of mele weapon in embedding
/:cl:
> Fix embedding

- code/modules/projectiles/guns/shotguns.dm
Изменил путь к прицелу с легаси на вполне существующий модуль в вендоре.
Это добавит более разнообразный геймплей для этого точно и мощного оружия. Если не будет хватать обзора, можно будет менять модуль во время передышек между боями.
:cl: 
fix: Now you can put a marine - T47 sight on the repeater
/:cl:
> Fix: Leicester Repeater

- code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
сразу скажу, что это не фиксит баг, когда воин не может двигаться во время лунджа/граба
кто-то умный(или не очень) добавил прок finish_lunge(), заменив при этом в сигналлере "COMSIG_MOVABLE_POST_THROW" clean_lunge_target() на этот новый прок
следующий решил вернуть старый вызов прока, но оставив новый
а третий, решил убрать один из этих проков
чё делает этот прок? да не ебу
1%ксенобаф и 99%кодбаф
:cl:
fix: proc finish_lunge now use in warrior lunge
/:cl:
> прок Finish_lunge снова вернулся в строй у вориера

- code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
- code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
- code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
- code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
- code/modules/mob/living/carbon/xenomorph/evolution.dm
- code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Позволяет квине выбирать касту для дееволва.
Разрешает дееволв в лявру.
Queen dictatorship
:cl:
add: Allows the queen to choose a cast for the deevolve.
add: Allows the queen to deevolve t1 castes.
fix: Xeno can no longer be devolved into forbidden castes (and delited)
/:cl:
> Advanced deevolve

- code/modules/clothing/suits/wiz_robe.dm
Так как пиджак подтип робы волшебника, она скрывает одежду под неё в результате чего выглядит криво и странно:
Теперь не будет:
> Fixes gentlemans coat hiding jumpsuit.

- code/modules/clothing/modular_armor/attachments/uniform.dm
Пистолеты теперь будут в первых слотах холстера вместо магазинов, потому что ты так или иначе либо заранее оставишь пистолет в первом слоте либо достанешь бесполезный магазин посреди боя.
> Changes places of guns with mags in the holsters so you can take it out quickly.
